// Refreshes the committed YouTube fallback snapshot.
// Run: node scripts/snapshot-youtube.mjs
import { writeFileSync } from "node:fs";
import { parseFeed, detectFormats, FEED_URL, CHANNEL_ID } from "../src/lib/youtube.js";

const response = await fetch(FEED_URL, {
  headers: { "User-Agent": "chaseintech.com snapshot" },
});
if (!response.ok) {
  console.error(`feed responded ${response.status}`);
  process.exit(1);
}

const videos = parseFeed(await response.text());
await detectFormats(videos);
if (videos.length === 0) {
  console.error("parsed zero entries — refusing to overwrite the snapshot");
  process.exit(1);
}

const payload = {
  capturedAt: new Date().toISOString().slice(0, 10),
  channelId: CHANNEL_ID,
  videos,
};

writeFileSync(
  new URL("../src/data/youtube-fallback.js", import.meta.url),
  `// Auto-generated by scripts/snapshot-youtube.mjs — do not edit by hand.\n` +
    `// Used only when the live RSS fetch fails during a build.\n` +
    `export const fallback = ${JSON.stringify(payload, null, 2)};\n`,
);

console.log(`snapshot written: ${videos.length} videos`);
for (const video of videos.slice(0, 5)) {
  console.log(`  ${video.publishedAt}  ${video.title}`);
}
